on:
  schedule:
    - cron: '15 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - run: cd ipa-to-elasticsearch && go run main.go
        env:
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PWD: ${{ secrets.ELASTIC_PWD }}
